### PR TITLE
Fix instanceList error

### LINKED ISSUE #1002: [Bug] Preprod frontend showing Server Error upon user login
**Describe the bug**
On every user login and page refresh on the pre-production CrownLabs website, a particular Server Error (screenshot below) pops up, which can be dismissed with no subsequent effect on user experience. Particularly, it affects the users who are not managers of any workspace.

**To Reproduce**
1. Go to https://preprod.crownlabs.polito.it
2. Login as a user who is not a manager of any workspace
3. See the error
4. Dismiss and refresh the page to see the error again

**Expected behavior**
No such error should appear

**Screenshots**

Image

**Additional context**
The full error message:
```{
  "message": "Could not invoke operation GET /apis/crownlabs.polito.it/v1alpha2/namespaces/{namespace}/instances",
  "path": [
    "instanceList"
  ],
  "extensions": {
    "method": "get",
    "path": "/apis/crownlabs.polito.it/v1alpha2/namespaces/{namespace}/instances",
    "url": "https://kubernetes.default.svc/apis/crownlabs.polito.it/v1alpha2/namespaces//instances",
    "statusText": "Forbidden",
    "statusCode": 403,
    "responseHeaders": {
      "audit-id": "018e33e7-9e5b-45d0-bf79-8c140bb937c4",
      "cache-control": "no-cache, private",
      "content-length": "328",
      "content-type": "application/json",
      "date": "Wed, 19 Nov 2025 17:33:52 GMT",
      "x-content-type-options": "nosniff",
      "x-kubernetes-pf-flowschema-uid": "5adc42ab-8e38-4ffa-bac8-33ce669da89f",
      "x-kubernetes-pf-prioritylevel-uid": "b0c9cc89-edb1-42d6-81c4-c8c5788bb45d"
    },
    "responseBody": {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "instances.crownlabs.polito.it is forbidden: User \"s316728\" cannot list resource \"instances\" in API group \"crownlabs.polito.it\" at the cluster scope",
      "reason": "Forbidden",
      "details": {
        "group": "crownlabs.polito.it",
        "kind": "instances"
      },
      "code": 403
    },
    "code": "INTERNAL_SERVER_ERROR",
    "stacktrace": [
      "GraphQLError: Could not invoke operation GET /apis/crownlabs.polito.it/v1alpha2/namespaces/{namespace}/instances",
      "    at graphQLErrorWithExtensions (/qlkube/node_modules/openapi-to-graphql/dist/index.js:2321:12)",
      "    at /qlkube/node_modules/openapi-to-graphql/dist/index.js:1871:23",
      "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at async /qlkube/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35",
      "    at async Promise.all (index 1)"
    ]
  }
}
```
I theorized that the cause may be this piece of code in `frontend/src/App.tsx`:
```  // Get all instances for quota calculations
  const { data: instancesData, refetch: refetchInstances } =
    useOwnedInstancesQuery({
      variables: { tenantNamespace: tenantNs || '' },
      skip: !tenantNs,
      onError: apolloErrorCatcher,
      fetchPolicy: 'cache-and-network',
    });
```
I think the `TenantContextProvider` has not yet supplied tenant data when the `App.tsx` is rendered for the first time. In that case, the `skip` option of the Apollo query should take effect, but it apparently doesn't, causing the request to contain an empty string instead of a namespace name.
This train of thought may be completely off the mark. I can try taking care of this provided someone provides initial directions.

### PR DESCRIPTION
**Pull request by SebastianMontoyaZ**
Fixed error popping up on app load
Fixes #1002

### CODE REVIEW

File: frontend/src/App.tsx [hunk 1]
```diff
@@ -40,15 +42,37 @@ function App() {
...
     } catch (error) {
       console.error('Error refreshing quota data:', error);
       apolloErrorCatcher(error as ApolloError);
     }
-  }, [refetchInstances, apolloErrorCatcher]);
+  }, [refetchInstances, apolloErrorCatcher, tenantNs]);
+
+  // Early return AFTER all hooks are called
+  if (!tenantNs) {
+    console.warn('Tenant namespace is undefined or null. Waiting...');
```
Comment (frisso) [inline frontend/src/App.tsx]:
```suggestion
    // Tenant namespace is undefined or null. Waiting...
```
